version: '3.1'

services:
  traefik:
    image: traefik:1.7
    restart: always
    ports:
      - 80:80
      - 443:443
      - 9023:9023
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - /opt/traefik/acme.json:/acme.json
    container_name: traefik

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus_data:/prometheus
      - ./prometheus/config:/config
    networks:
      - web
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.backend=prometheus"
      - "traefik.frontend.rule=Host:prometheus.datenchaos.ctfl.space"
      - "traefik.docker.network=web"
      - "traefik.port=9090"
    container_name: prometheus
    links:
    - traefik:traefik
    - grafana:grafana

  grafana:
    image: grafana/grafana:5.2.1
    ports:
    - 8080:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - web
    restart: always
    user: "104"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.frontend.rule=Host:grafana.datenchaos.ctfl.space"
      - "traefik.docker.network=web"
      - "traefik.port=3000"
    container_name: grafana

  cadvisor-exporter:
    container_name: "cadvisor-exporter"
    image: google/cadvisor
    networks:
      - web
    restart: always
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    restart: always
    networks:
      - web
    env_file:
      - './influxdb/env.influxdb'
    volumes:
      - ./influxdb/data:/var/lib/influxdb

volumes:
  prometheus_data: {}

networks:
  web:
    external: true
