version: '3.1'

services:
  grafana:
    image: grafana/grafana:latest
    volumes:
      - "./:/var/lib/grafana"
    networks:
      - web
    enviroment:
     - "GF_SERVER_ROOT_URL=https://datenchaos.ctfl.space/grafana"
    #  add grafana plugins to be installed on container startup
     - "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.frontend.rule=Host:datenchaos.ctfl.space"
      - "traefik.frontend.rule=PATH:/grafana"
      - "traefik.docker.network=web"
      - "traefik.port=3000"
    container_name: grafana
networks:
  web:
    external: true
