version: '3.1'

services:
  grafana:
    image: grafana/grafana:latest
    volumes:
      - "./:/var/lib/grafana"
    networks:
      - web
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.frontend.rule=Host:grafana.datenchaos.ctfl.space"
      - "traefik.docker.network=web"
      - "traefik.port=3000"
    container_name: grafana
networks:
  web:
    external: true
